### ISSUE TITLE
型号6sp  9.3.2 运行电池栏不见 

### ISSUE THREAD

**Issue by xrefLee** [ripperhe/Debugo#1]

**Comment by ripperhe** [comment]
你看一下控制器里是不是这个方法 - (BOOL)prefersStatusBarHidden 返回了YES，或者是其他一些状态栏的设置有问题。公司的工程里一直在用，几个测试机运行暂未发现这个问题，不过和你设备信息完全符合的手机我这里没有，不太好调试。。。

**Comment by ripperhe** [comment]
我今天用同事的手机测了一下，9.3.2系统确实出现了这个问题，现在已经修复了。解决方案是在悬浮球的UIWindow的rootViewController的 - (BOOL)prefersStatusBarHidden 方法中返回了YES
