### ISSUE TITLE
想问下悬浮球，闲置的时候，怎么只显示一半？

### ISSUE THREAD

**Issue by joshua-hua** [ripperhe/Debugo#2]
想问下悬浮球，闲置的时候，怎么只显示一半？就是多长时间我没有点击悬浮球，悬浮球收起来一半。

**Comment by ripperhe** [comment]
只要放手，默认会收起来一部分

**Comment by joshua-hua** [comment]
想问下，旋转屏幕的时候，四个方向会出现黑色正方形，不知道是什么引起的，想问下这个怎么解决呢?

**Comment by ripperhe** [comment]
你尝试一下最新的这个代码，看还有没有这个问题
